"""Add multi-tenancy

Revision ID: 5a37539634cc
Revises: 835d6b600a15
Create Date: 2026-06-21 08:10:38.299965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a37539634cc'
down_revision: Union[str, Sequence[str], None] = '835d6b600a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.add_column('customers', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'])
    op.add_column('invoices', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'businesses', ['business_id'], ['id'])
    op.add_column('payments', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'businesses', ['business_id'], ['id'])
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'business_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'business_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'business_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=1)
    op.drop_column('customers', 'business_id')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
