"""Add role to users

Revision ID: 6abde7c21add
Revises: 9ca743b0ece1
Create Date: 2026-06-22 08:04:46.429973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6abde7c21add'
down_revision: Union[str, Sequence[str], None] = '9ca743b0ece1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_email'), table_name='reset_tokens')
    op.drop_index(op.f('ix_reset_tokens_id'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reset_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('reset_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reset_tokens_id'), 'reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_reset_tokens_email'), 'reset_tokens', ['email'], unique=False)
    # ### end Alembic commands ###
