"""refactor models

Revision ID: 835d6b600a15
Revises: a165c8e042ea
Create Date: 2026-06-18 17:23:41.985574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835d6b600a15'
down_revision: Union[str, Sequence[str], None] = 'a165c8e042ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'customers', ['email'])
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('invoices', 'balance')
    op.add_column('payments', sa.Column('invoice_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'channel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'payments', ['reference'])
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'channel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('payments', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'payment_date')
    op.drop_column('payments', 'invoice_id')
    op.add_column('invoices', sa.Column('balance', sa.FLOAT(), nullable=False))
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('invoices', 'created_at')
    op.drop_constraint(None, 'customers', type_='unique')
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
