"""Add business_id columns

Revision ID: 9ca743b0ece1
Revises: 5a37539634cc
Create Date: 2026-06-21 08:17:26.055628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca743b0ece1'
down_revision: Union[str, Sequence[str], None] = '5a37539634cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.add_column('invoices', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_id')
    op.drop_column('payments', 'business_id')
    op.drop_column('invoices', 'business_id')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=1)
    op.drop_column('customers', 'business_id')
    # ### end Alembic commands ###
